### ISSUE TITLE
wallpaper color - Black - AMOLED

### ISSUE THREAD

**Issue by mg1234567** [redwarp/gif-wallpaper#279] opened 2022-10-07 20:08 UTC
Please allow the ability to chose any color for the background. 
In my case, I want to use a black (dark) wallpaper.
 
But, I am not presented with every wallpaper color. 

Please support black AMOLED screens.

**Comment by redwarp** [comment] 2022-10-07 20:11
Duplicate of #277 ;-)

**Closed by redwarp** 2022-10-07 20:11 UTC
